ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_1.fits ./test_psf_DES_1  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_2.fits ./test_psf_DES_2  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_3.fits ./test_psf_DES_3  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_4.fits ./test_psf_DES_4  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_5.fits ./test_psf_DES_5  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_6.fits ./test_psf_DES_6  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_7.fits ./test_psf_DES_7  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_8.fits ./test_psf_DES_8  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_9.fits ./test_psf_DES_9  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_10.fits ./test_psf_DES_10  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_11.fits ./test_psf_DES_11  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_12.fits ./test_psf_DES_12  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_13.fits ./test_psf_DES_13  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_14.fits ./test_psf_DES_14  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_15.fits ./test_psf_DES_15  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_16.fits ./test_psf_DES_16  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_17.fits ./test_psf_DES_17  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_18.fits ./test_psf_DES_18  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_19.fits ./test_psf_DES_19  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_20.fits ./test_psf_DES_20  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_21.fits ./test_psf_DES_21  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_22.fits ./test_psf_DES_22  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_23.fits ./test_psf_DES_23  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_24.fits ./test_psf_DES_24  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_25.fits ./test_psf_DES_25  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_26.fits ./test_psf_DES_26  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_27.fits ./test_psf_DES_27  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_28.fits ./test_psf_DES_28  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_29.fits ./test_psf_DES_29  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_30.fits ./test_psf_DES_30  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_31.fits ./test_psf_DES_31  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_32.fits ./test_psf_DES_32  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_33.fits ./test_psf_DES_33  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_34.fits ./test_psf_DES_34  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_35.fits ./test_psf_DES_35  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_36.fits ./test_psf_DES_36  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_37.fits ./test_psf_DES_37  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_38.fits ./test_psf_DES_38  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_39.fits ./test_psf_DES_39  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_40.fits ./test_psf_DES_40  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_41.fits ./test_psf_DES_41  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_42.fits ./test_psf_DES_42  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_43.fits ./test_psf_DES_43  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_44.fits ./test_psf_DES_44  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_45.fits ./test_psf_DES_45  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_46.fits ./test_psf_DES_46  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_47.fits ./test_psf_DES_47  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_48.fits ./test_psf_DES_48  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_49.fits ./test_psf_DES_49  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_50.fits ./test_psf_DES_50  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_51.fits ./test_psf_DES_51  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_52.fits ./test_psf_DES_52  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_53.fits ./test_psf_DES_53  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_54.fits ./test_psf_DES_54  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_55.fits ./test_psf_DES_55  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_56.fits ./test_psf_DES_56  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_57.fits ./test_psf_DES_57  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_58.fits ./test_psf_DES_58  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_59.fits ./test_psf_DES_59  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_60.fits ./test_psf_DES_60  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_61.fits ./test_psf_DES_61  
ipython test_psf_DES.py ../imagenes-LN-PSF/im_06_62.fits ./test_psf_DES_62  
